# Global settings.
timezone: Europe/London

# Site settings.
title: kieranbamforth.me
description: A braindump, mostly.
url: https://www.kieranbamforth.me
permalink: post/:title

# Jekyll paginate
paginate: 25

# Build settings.
markdown: kramdown

# Chalk settings.
rss_enabled: true
name: kieranbamforth.me
social:
    github: kieran-bamforth
    twitter: kieran_bamforth
    email: hello@kieranbamforth.me
    linkedin: kieran-bamforth
ga_analytics: UA-58001717-3
disqus_shortname: kieranbamforth
scrollappear_enabled: false
local_fonts: true
theme_toggle: true

# Amplify settings.
author_image: "/assets/author.jpg"
# bio: A software engineer, keen on leadership & productivity (invite me to your parties :dancer:).

plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - amp-jekyll

